import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const GRAPPLER_A: CharacterDef = {
  id: "grappler-a",
  name: "Capitan",
  archetype: "grappler-a",
  blurb: "Massiv grappler med järngrepp. Absorberar inkommande attacker med rå pansar, kliver obevekligt framåt och krossar med förödande kommandokast.",
  strengths: ["Extremt hög skada", "Oblockerbara kommandokast", "Pansar på utvalda attacker"],
  weaknesses: ["Mycket långsam förflyttning", "Svag mot intensiv zoning", "Stora träffytor"],
  combo: "Snabb stöt -> Capitan Power Slam (kommandokast)",
  antiAir: "Hög box eller Gripande näve",
  approach: "Tålmodig framryckning med pansar och skräckinjagande närvaro",
  punish: "Hög box -> Capitan Power Slam -> Super",
  walkSpeed: 25,
  backWalkSpeed: 18,
  jumpVy: 100,
  jumpStartup: 5,
  landRecovery: 4,
  airControl: 10,
  weight: 1120,
  throwDamage: 140,
  throwTechWindow: 8,
  pushbox: { ...DEFAULT_PUSHBOX, w: 180 },
  hurtStand: [
    { x: -95, y: 0, w: 190, h: 220 },
    { x: -90, y: 220, w: 180, h: 210 },
  ],
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#b91c1c", "#f87171"],
  animationProfileId: "grappler-a",
  modelUrl: "/models/Soldier.glb",
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_chop",
    throw: "throw",
    special1: "cable_grab",
    special2: "power_cable",
    super: "blackout_super",
  },
  moves: {
    lp: {
      id: "lp",
      name: "Tung stöt",
      startup: 5,
      active: 3,
      recovery: 8,
      damage: 45,
      hitstun: 13,
      blockstun: 10,
      hitstop: 5,
      pushback: 40,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 50, y: 210, w: 85, h: 60 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "cable_grab", "blackout_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Tvåhandsdräm",
      startup: 11,
      active: 4,
      recovery: 18,
      damage: 115,
      hitstun: 20,
      blockstun: 14,
      hitstop: 8,
      pushback: 90,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 55, y: 190, w: 140, h: 90 }],
      meterGainOnHit: 70,
      meterGainOnBlock: 30,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["cable_grab", "blackout_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Stamp",
      startup: 6,
      active: 3,
      recovery: 9,
      damage: 40,
      hitstun: 12,
      blockstun: 8,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 45, y: 20, w: 100, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["cable_grab"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Tung bensvep",
      startup: 12,
      active: 4,
      recovery: 20,
      damage: 105,
      hitstun: 22,
      blockstun: 11,
      hitstop: 6,
      pushback: 90,
      knockback: 85,
      launch: 35,
      category: "LOW",
      hitboxes: [{ x: 50, y: 15, w: 150, h: 65 }],
      meterGainOnHit: 60,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["blackout_super"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_chop: {
      id: "air_chop",
      name: "Luftkross",
      startup: 7,
      active: 5,
      recovery: 12,
      damage: 80,
      hitstun: 16,
      blockstun: 12,
      hitstop: 6,
      pushback: 55,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 45, y: 130, w: 130, h: 85 }],
      meterGainOnHit: 50,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Grundkast",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 140,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 150,
      knockback: 100,
      launch: 70,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 70, w: 105, h: 240 },
      meterGainOnHit: 70,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    cable_grab: {
      id: "cable_grab",
      name: "Kabel-lås",
      startup: 6,
      active: 3,
      recovery: 24,
      damage: 175,
      hitstun: 30,
      blockstun: 0,
      hitstop: 10,
      pushback: 120,
      knockback: 110,
      launch: 80,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 70, w: 115, h: 240 },
      commandGrab: true,
      meterGainOnHit: 80,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "special_grab",
    },
    power_cable: {
      id: "power_cable",
      name: "Kraftkabel",
      startup: 13,
      active: 5,
      recovery: 22,
      damage: 110,
      hitstun: 22,
      blockstun: 12,
      hitstop: 7,
      pushback: 95,
      knockback: 90,
      launch: 20,
      category: "MID",
      hitboxes: [{ x: 50, y: 160, w: 140, h: 100 }],
      armorHits: 1,
      meterGainOnHit: 60,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 25,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["blackout_super"] },
      airOk: false,
      lowPose: false,
      animation: "special_armor",
    },
    blackout_super: {
      id: "blackout_super",
      name: "Total Nedsläckning",
      startup: 4,
      active: 4,
      recovery: 34,
      damage: 340,
      hitstun: 40,
      blockstun: 0,
      hitstop: 14,
      pushback: 160,
      knockback: 140,
      launch: 100,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 70, w: 125, h: 250 },
      commandGrab: true,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 0,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 5,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
