import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const GRAPPLER_B: CharacterDef = {
  id: "grappler-b",
  name: "Rack",
  archetype: "grappler-b",
  blurb: "Massiv serverchassibyggare. Oerhörd massa och förödande grepp som monterar ned allt motstånd.",
  strengths: ["Högsta kastskadan", "2 pansarträffar på markattack", "Mycket hög tålighet och vikt"],
  weaknesses: ["Långsammast i spelet", "Stor måltavla för projektiler", "Kräver tålmodig spacing"],
  combo: "Låg spark -> Rack-montering",
  antiAir: "Tvåhandslyft eller Rack-montering",
  approach: "Pansrad framryckning och hörnpress",
  punish: "Hög box -> Rack-montering -> Super",
  walkSpeed: 23,
  backWalkSpeed: 16,
  jumpVy: 98,
  jumpStartup: 5,
  landRecovery: 4,
  airControl: 9,
  weight: 1160,
  throwDamage: 145,
  throwTechWindow: 8,
  pushbox: { ...DEFAULT_PUSHBOX, w: 190 },
  hurtStand: [
    { x: -100, y: 0, w: 200, h: 220 },
    { x: -95, y: 220, w: 190, h: 220 },
  ],
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#7f1d1d", "#fca5a5"],
  animationProfileId: "grappler-b",
  modelUrl: "/models/Soldier.glb",
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_press",
    throw: "throw",
    special1: "rack_suplex",
    special2: "ground_breaker",
    super: "disaster_recovery_super",
  },
  moves: {
    lp: {
      id: "lp",
      name: "Tung labb",
      startup: 5,
      active: 3,
      recovery: 8,
      damage: 46,
      hitstun: 13,
      blockstun: 10,
      hitstop: 5,
      pushback: 42,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 50, y: 210, w: 85, h: 65 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "rack_suplex", "disaster_recovery_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Serverplåt",
      startup: 12,
      active: 4,
      recovery: 19,
      damage: 120,
      hitstun: 21,
      blockstun: 14,
      hitstop: 8,
      pushback: 95,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 55, y: 190, w: 145, h: 95 }],
      meterGainOnHit: 70,
      meterGainOnBlock: 30,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["rack_suplex", "disaster_recovery_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Jordstamp",
      startup: 6,
      active: 3,
      recovery: 9,
      damage: 42,
      hitstun: 12,
      blockstun: 8,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 45, y: 15, w: 105, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["rack_suplex"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Sockelsvep",
      startup: 12,
      active: 4,
      recovery: 21,
      damage: 110,
      hitstun: 23,
      blockstun: 11,
      hitstop: 6,
      pushback: 95,
      knockback: 90,
      launch: 35,
      category: "LOW",
      hitboxes: [{ x: 50, y: 10, w: 155, h: 70 }],
      meterGainOnHit: 60,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["disaster_recovery_super"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_press: {
      id: "air_press",
      name: "Rack-dyk",
      startup: 8,
      active: 5,
      recovery: 13,
      damage: 85,
      hitstun: 17,
      blockstun: 12,
      hitstop: 6,
      pushback: 60,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 45, y: 120, w: 135, h: 90 }],
      meterGainOnHit: 50,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Grundlyft",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 145,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 155,
      knockback: 105,
      launch: 70,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 70, w: 110, h: 240 },
      meterGainOnHit: 70,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    rack_suplex: {
      id: "rack_suplex",
      name: "Rack-montering",
      startup: 5,
      active: 3,
      recovery: 25,
      damage: 185,
      hitstun: 30,
      blockstun: 0,
      hitstop: 10,
      pushback: 130,
      knockback: 120,
      launch: 85,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 70, w: 120, h: 240 },
      commandGrab: true,
      meterGainOnHit: 85,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "special_grab",
    },
    ground_breaker: {
      id: "ground_breaker",
      name: "Strömavbrott",
      startup: 14,
      active: 5,
      recovery: 23,
      damage: 115,
      hitstun: 24,
      blockstun: 12,
      hitstop: 7,
      pushback: 100,
      knockback: 95,
      launch: 30,
      category: "LOW",
      hitboxes: [{ x: 50, y: 10, w: 160, h: 100 }],
      armorHits: 2,
      meterGainOnHit: 65,
      meterGainOnBlock: 25,
      meterCost: 0,
      chip: 25,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["disaster_recovery_super"] },
      airOk: false,
      lowPose: true,
      animation: "special_armor",
    },
    disaster_recovery_super: {
      id: "disaster_recovery_super",
      name: "Katastrofåterställning",
      startup: 4,
      active: 4,
      recovery: 36,
      damage: 350,
      hitstun: 40,
      blockstun: 0,
      hitstop: 15,
      pushback: 170,
      knockback: 150,
      launch: 110,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 70, w: 130, h: 250 },
      commandGrab: true,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 0,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 5,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
