import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const HYBRID_B: CharacterDef = {
  id: "hybrid-b",
  name: "Cloud",
  archetype: "hybrid-b",
  blurb: "Molntjänstspecialist som kombinerar fjärrstyrda blixtattacker med elastisk rörlighet.",
  strengths: ["Vertikala attacker från ovan", "Bra neutral poke med god räckvidd", "Balanserad flytkänsla"],
  weaknesses: ["Svävande hopp ger långsam landning", "Kräver framförhållning på fällor", "Måttlig närstridsskada"],
  combo: "Snabb stöt -> Låg länk -> Molndrag",
  antiAir: "Blixtnedslag eller Hög stöt",
  approach: "Blixtnedslag på avstånd följt av Molndrag framåt",
  punish: "Hög box -> Molndrag -> Molnstorm",
  walkSpeed: 34,
  backWalkSpeed: 24,
  jumpVy: 108,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 15,
  weight: 980,
  throwDamage: 115,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#0d9488", "#5eead4"],
  animationProfileId: "hybrid-b",
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_strike",
    throw: "throw",
    special1: "lightning_strike",
    special2: "cloud_glide",
    super: "cloudstorm_super",
  },
  moves: {
    lp: {
      id: "lp",
      name: "Molnstöt",
      startup: 4,
      active: 3,
      recovery: 6,
      damage: 38,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 36,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 45, y: 220, w: 82, h: 52 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "cloud_glide", "cloudstorm_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Serverstöt",
      startup: 9,
      active: 4,
      recovery: 15,
      damage: 92,
      hitstun: 18,
      blockstun: 12,
      hitstop: 6,
      pushback: 72,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 50, y: 215, w: 130, h: 65 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["cloud_glide", "cloudstorm_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Kondensspark",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 36,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 32,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 20, w: 100, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "cloud_glide"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Tornado-svep",
      startup: 10,
      active: 4,
      recovery: 18,
      damage: 92,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 82,
      knockback: 75,
      launch: 25,
      category: "LOW",
      hitboxes: [{ x: 45, y: 15, w: 145, h: 60 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["cloudstorm_super"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_strike: {
      id: "air_strike",
      name: "Svängande molnspark",
      startup: 6,
      active: 5,
      recovery: 10,
      damage: 68,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 48,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 135, w: 120, h: 75 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Molnkast",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 115,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 140,
      knockback: 85,
      launch: 55,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    lightning_strike: {
      id: "lightning_strike",
      name: "Blixtnedslag",
      startup: 15,
      active: 5,
      recovery: 20,
      damage: 80,
      hitstun: 18,
      blockstun: 12,
      hitstop: 5,
      pushback: 65,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [],
      zone: {
        lifetime: 40,
        hitbox: { x: 180, y: 0, w: 90, h: 320 },
        damage: 80,
        category: "OVERHEAD",
        maxConcurrent: 1,
        hitstun: 18,
        blockstun: 12,
      },
      meterGainOnHit: 50,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 18,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "special_shot",
    },
    cloud_glide: {
      id: "cloud_glide",
      name: "Molndrag",
      startup: 10,
      active: 6,
      recovery: 17,
      damage: 95,
      hitstun: 20,
      blockstun: 11,
      hitstop: 6,
      pushback: 85,
      knockback: 75,
      launch: 20,
      category: "MID",
      hitboxes: [{ x: 45, y: 160, w: 140, h: 90 }],
      meterGainOnHit: 60,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 18,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["cloudstorm_super"] },
      airOk: false,
      lowPose: false,
      animation: "special_tackle",
    },
    cloudstorm_super: {
      id: "cloudstorm_super",
      name: "Molnstorm",
      startup: 8,
      active: 12,
      recovery: 28,
      damage: 280,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 180,
      knockback: 140,
      launch: 110,
      category: "MID",
      hitboxes: [{ x: 30, y: 120, w: 320, h: 220 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 60,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 8,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
