import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const HYBRID_A: CharacterDef = {
  id: "hybrid-a",
  name: "Ekander",
  archetype: "hybrid-a",
  blurb: "Hybrid Zoner/Grappler. Dominerar mellanavståndet med obehagliga fällor och straffar varje tvekan med blixtsnabba oväntade kast.",
  strengths: ["Kombination av distanskontroll och kast", "Svårläst mixup-spel", "Oförutsägbara anfallsvinklar"],
  weaknesses: ["Kräver strikt lägesbedömning", "Lägre bas-skada på rena normals", "Sårbar vid felbedömda kast"],
  combo: "Distansstöt -> Låg spark -> Ekander Trap & Slam",
  antiAir: "Hög spark eller Gripande kast",
  approach: "Tvinga fram blockering med zoner och kliv in för grepp",
  punish: "Hög box -> Ekander Slam -> Super",
  walkSpeed: 38,
  backWalkSpeed: 28,
  jumpVy: 118,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 18,
  weight: 970,
  throwDamage: 115,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#9333ea", "#c084fc"],
  animationProfileId: "hybrid-a",
  modelUrl: "/models/RobotExpressive.glb",
  tagline: "The Heavy Momentum",
  power: 8,
  speed: 7,
  range: 6,
  signature: "Ekander Roll",
  superName: "TERMINAL VELOCITY",
  playstyle: "En oförutsägbar hybrid zoner/grappler som rullar fram med massiv rörelseenergi och förvandlar motståndarens försvar till grus.",
  voiceBarks: {
    special: "EKANDER ROLL!",
    super: "TERMINAL VELOCITY!",
    win: "CANNOT STOP THIS MASS!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_strike",
    throw: "throw",
    special1: "ekander_roll",
    special2: "dive_kick",
    super: "terminal_velocity_super",
  },
  moves: {
    lp: {
      id: "lp",
      name: "Meat Jab",
      startup: 4,
      active: 3,
      recovery: 6,
      damage: 37,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 45, y: 220, w: 80, h: 50 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "ekander_roll", "terminal_velocity_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Heavy Slap",
      startup: 8,
      active: 4,
      recovery: 14,
      damage: 92,
      hitstun: 17,
      blockstun: 11,
      hitstop: 6,
      pushback: 68,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 50, y: 220, w: 120, h: 65 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["ekander_roll", "terminal_velocity_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Fat Foot",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 35,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 32,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 25, w: 100, h: 48 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "ekander_roll"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Belly Bounce Kick",
      startup: 9,
      active: 4,
      recovery: 17,
      damage: 90,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 78,
      knockback: 70,
      launch: 25,
      category: "LOW",
      hitboxes: [{ x: 45, y: 20, w: 140, h: 60 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["terminal_velocity_super"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_strike: {
      id: "air_strike",
      name: "Luftspark",
      startup: 6,
      active: 5,
      recovery: 10,
      damage: 68,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 48,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 130, w: 120, h: 75 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Nod-kast",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 115,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 140,
      knockback: 85,
      launch: 55,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    dive_kick: {
      id: "dive_kick",
      name: "Nätverksdyk",
      startup: 7,
      active: 8,
      recovery: 12,
      damage: 90,
      hitstun: 20,
      blockstun: 12,
      hitstop: 6,
      pushback: 65,
      knockback: 40,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 35, y: 20, w: 110, h: 90 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 15,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "special_dive",
    },
    ekander_roll: {
      id: "ekander_roll",
      name: "Ekander Roll",
      startup: 10,
      active: 6,
      recovery: 18,
      damage: 100,
      hitstun: 22,
      blockstun: 11,
      hitstop: 6,
      pushback: 80,
      knockback: 75,
      launch: 35,
      category: "MID",
      hitboxes: [{ x: 45, y: 160, w: 130, h: 100 }],
      meterGainOnHit: 60,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 20,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["terminal_velocity_super"] },
      airOk: false,
      lowPose: false,
      animation: "special_tackle",
    },
    terminal_velocity_super: {
      id: "terminal_velocity_super",
      name: "TERMINAL VELOCITY",
      startup: 7,
      active: 12,
      recovery: 28,
      damage: 285,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 180,
      knockback: 145,
      launch: 115,
      category: "MID",
      hitboxes: [{ x: 40, y: 140, w: 280, h: 180 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 60,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 7,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
