import type { CharacterDef } from "@aipuf/contracts";
import { airPunch, crouchKit, DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const HYBRID_B: CharacterDef = {
  id: "hybrid-b",
  name: "Bulgarian Copper Thief",
  archetype: "hybrid-b",
  blurb: "Kofot i ansiktet och en rusning in i elskåpet. Inga blixtar från skyn.",
  strengths: ["Lång kofot", "Rush-special", "Hoppspark"],
  weaknesses: ["Straffas på whiff", "Tunn på nära håll om rushen blockas"],
  combo: "Jab → låg spark → Unauthorized Entry",
  antiAir: "Kofot-overhead eller jump kick",
  approach: "Dash, rusning, hopp-in",
  punish: "Tung box → Rush → Super",
  walkSpeed: 6,
  backWalkSpeed: 4,
  dashSpeed: 22,
  jumpVy: 51,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 15,
  weight: 980,
  throwDamage: 115,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#0d9488", "#5eead4"],
  animationProfileId: "hybrid-b",
  modelUrl: "/models/Xbot.glb",
  tagline: "The Grid Raider",
  power: 7,
  speed: 8,
  range: 8,
  signature: "Unauthorized Entry",
  superName: "THE GRID IS MINE",
  playstyle: "Kofot-overhead, rusning in, koppar i nävarna.",
  voiceBarks: {
    special: "UNAUTHORIZED ENTRY!",
    super: "THE GRID IS MINE!",
    win: "ALL YOUR COPPER BELONGS TO ME!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_strike",
    throw: "throw",
    special1: "unauthorized_entry",
    special2: "lightning_strike",
    super: "the_grid_is_mine_super",
  },
  moves: {
    ...crouchKit(["lk", "hp", "hk", "unauthorized_entry", "the_grid_is_mine_super"]),
    air_punch: airPunch("Kabelkrok"),
    lp: {
      id: "lp",
      name: "Grab-and-Go Jab",
      startup: 4,
      active: 3,
      recovery: 6,
      damage: 38,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 36,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 45, y: 220, w: 82, h: 52 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "unauthorized_entry", "the_grid_is_mine_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Cable Whip",
      startup: 9,
      active: 4,
      recovery: 15,
      damage: 92,
      hitstun: 18,
      blockstun: 12,
      hitstop: 6,
      pushback: 72,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 50, y: 280, w: 130, h: 70 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["unauthorized_entry", "the_grid_is_mine_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Copper Shin",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 36,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 32,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 20, w: 100, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "unauthorized_entry"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Crowbar Kick",
      startup: 10,
      active: 4,
      recovery: 18,
      damage: 92,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 82,
      knockback: 75,
      launch: 25,
      category: "LOW",
      hitboxes: [{ x: 45, y: 15, w: 145, h: 60 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["the_grid_is_mine_super"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_strike: {
      id: "air_strike",
      name: "Svängande molnspark",
      startup: 6,
      active: 5,
      recovery: 10,
      damage: 68,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 48,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 135, w: 120, h: 75 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Molnkast",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 115,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 140,
      knockback: 85,
      launch: 55,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    lightning_strike: {
      id: "lightning_strike",
      name: "Crowbar Overhead",
      startup: 12,
      active: 4,
      recovery: 18,
      damage: 88,
      hitstun: 18,
      blockstun: 12,
      hitstop: 6,
      pushback: 55,
      knockback: 20,
      launch: 10,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 160, w: 130, h: 110 }],
      advance: 6,
      meterGainOnHit: 50,
      meterGainOnBlock: 18,
      meterCost: 0,
      chip: 10,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward", "dash"],
      cancels: { hit: ["the_grid_is_mine_super"] },
      airOk: false,
      lowPose: false,
      animation: "special",
    },
    unauthorized_entry: {
      id: "unauthorized_entry",
      name: "Unauthorized Entry",
      startup: 10,
      active: 6,
      recovery: 17,
      damage: 95,
      hitstun: 20,
      blockstun: 11,
      hitstop: 6,
      pushback: 85,
      knockback: 75,
      launch: 20,
      category: "MID",
      hitboxes: [{ x: 45, y: 160, w: 140, h: 90 }],
      advance: 15,
      meterGainOnHit: 60,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 18,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["the_grid_is_mine_super"] },
      airOk: false,
      lowPose: false,
      animation: "special_tackle",
    },
    the_grid_is_mine_super: {
      id: "the_grid_is_mine_super",
      name: "THE GRID IS MINE",
      startup: 8,
      active: 12,
      recovery: 28,
      damage: 280,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 180,
      knockback: 140,
      launch: 110,
      category: "MID",
      hitboxes: [{ x: 30, y: 120, w: 320, h: 220 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 60,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 8,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
