import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const SHOTO_A: CharacterDef = {
  id: "shoto-a",
  name: "Irstababben",
  archetype: "shoto-a",
  blurb: "Teknisk och skoningslös shoto från Irsta. Klassisk neutral, blixtrande uppercut och kompromisslös precision i varje stöt.",
  strengths: ["Allsidig verktygslåda", "Oslagbar anti-air uppercut", "Goda combo-länkar"],
  weaknesses: ["Saknar extrema spetsegenskaper", "Förutsägbar spelstil", "Kräver ren exekvering"],
  combo: "Snabb stöt -> Låg spark -> Irsta Uppercut",
  antiAir: "Irsta Uppercut eller Hög box",
  approach: "Kasta Projektil och stöt framåt",
  punish: "Hög box -> Uppercut -> Super",
  walkSpeed: 36,
  backWalkSpeed: 26,
  jumpVy: 110,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 14,
  weight: 1000,
  throwDamage: 120,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#16a34a", "#facc15"],
  animationProfileId: "shoto-a",
  modelUrl: "/models/RobotExpressive.glb",
  tagline: "Pizzabagaren från Irsta",
  power: 7,
  speed: 7,
  range: 7,
  signature: "Hawaii Blast",
  superName: "Irsta Speciale",
  playstyle: "Balanserad protagonist med god neutral, pizzaspadens räckvidd och en ananaseldklotet Hawaii Blast.",
  voiceBarks: {
    special: "HAWAII!",
    super: "IRSTA SPECIALE!",
    win: "SMAKLIG MÅLTID!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_kick",
    throw: "throw",
    special1: "hawaii_blast",
    special2: "spade_uppercut",
    super: "irsta_speciale",
  },
  moves: {
    lp: {
      id: "lp",
      name: "Owner’s Jab",
      startup: 4,
      active: 3,
      recovery: 6,
      damage: 38,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 45, y: 220, w: 85, h: 55 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "hawaii_blast", "spade_uppercut", "irsta_speciale"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Pizza Spade Smash",
      startup: 8,
      active: 4,
      recovery: 14,
      damage: 95,
      hitstun: 18,
      blockstun: 12,
      hitstop: 6,
      pushback: 70,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 50, y: 225, w: 125, h: 65 }],
      meterGainOnHit: 60,
      meterGainOnBlock: 25,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["hawaii_blast", "spade_uppercut", "irsta_speciale"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Pizzeria Low Kick",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 35,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 32,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 25, w: 100, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 10,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "hawaii_blast", "spade_uppercut"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Oven Door Kick",
      startup: 9,
      active: 4,
      recovery: 16,
      damage: 85,
      hitstun: 19,
      blockstun: 10,
      hitstop: 6,
      pushback: 80,
      knockback: 60,
      launch: 10,
      category: "MID",
      hitboxes: [{ x: 45, y: 150, w: 120, h: 80 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["spade_uppercut", "irsta_speciale"] },
      airOk: false,
      lowPose: false,
      animation: "kick_heavy",
    },
    air_kick: {
      id: "air_kick",
      name: "Luftspark",
      startup: 6,
      active: 5,
      recovery: 10,
      damage: 70,
      hitstun: 14,
      blockstun: 10,
      hitstop: 5,
      pushback: 50,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 80, w: 110, h: 70 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 18,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Grundkast",
      startup: 4,
      active: 2,
      recovery: 16,
      damage: 120,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 140,
      knockback: 90,
      launch: 60,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    hawaii_blast: {
      id: "hawaii_blast",
      name: "Hawaii Blast",
      startup: 11,
      active: 4,
      recovery: 19,
      damage: 75,
      hitstun: 16,
      blockstun: 12,
      hitstop: 4,
      pushback: 60,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [],
      projectile: {
        vx: 85,
        vy: 0,
        lifetime: 70,
        hitbox: { x: -25, y: 190, w: 55, h: 45 },
        damage: 75,
        category: "HIGH",
        maxConcurrent: 1,
        hitstun: 16,
        blockstun: 12,
        hitstop: 4,
        pushback: 60,
        meterGainOnHit: 50,
        chip: 15,
      },
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["irsta_speciale"] },
      airOk: false,
      lowPose: false,
      animation: "special_shot",
    },
    spade_uppercut: {
      id: "spade_uppercut",
      name: "Pizza Spade Uppercut",
      startup: 5,
      active: 6,
      recovery: 24,
      damage: 120,
      hitstun: 25,
      blockstun: 14,
      hitstop: 6,
      pushback: 80,
      knockback: 90,
      launch: 100,
      category: "MID",
      hitboxes: [{ x: 30, y: 180, w: 100, h: 220 }],
      meterGainOnHit: 65,
      meterGainOnBlock: 25,
      meterCost: 0,
      chip: 20,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 5,
      allowed: ["idle", "walkForward", "walkBackward", "crouch"],
      cancels: { hit: ["irsta_speciale"] },
      airOk: false,
      lowPose: false,
      animation: "special_dp",
    },
    irsta_speciale: {
      id: "irsta_speciale",
      name: "Irsta Speciale",
      startup: 7,
      active: 10,
      recovery: 30,
      damage: 285,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 180,
      knockback: 140,
      launch: 110,
      category: "MID",
      hitboxes: [{ x: 40, y: 160, w: 260, h: 200 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 60,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 7,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
