import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const SHOTO_B: CharacterDef = {
  id: "shoto-b",
  name: "Goonström",
  archetype: "shoto-b",
  blurb: "Aggressiv och intensiv shoto. Rusar in med vilda sparkkombinationer och skoningslös offensiv som knäcker motståndarens gard.",
  strengths: ["Mycket snabb förflyttning", "Kraftfulla rusningsattacker", "Goda combo-förlängningar"],
  weaknesses: ["Något lägre tålighet", "Kräver avståndskontroll för att inte straffas", "Svagare projektiler"],
  combo: "Snabb stöt -> Låg spark -> Goon-rush",
  antiAir: "Hög spark eller Flygande knä",
  approach: "Goon-rush framåt eller snabbt hopp",
  punish: "Hög box -> Goon-rush -> Max Super",
  walkSpeed: 42,
  backWalkSpeed: 30,
  jumpVy: 115,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 16,
  weight: 960,
  throwDamage: 110,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#ea580c", "#fb923c"],
  animationProfileId: "shoto-b",
  modelUrl: "/models/RobotExpressive.glb",
  tagline: "The Relentless Stalker",
  power: 7,
  speed: 9,
  range: 7,
  signature: "Goon Blast",
  superName: "MAXIMUM GOON",
  playstyle: "En intensiv och hyperaggressiv shoto som rusar in med vilda kombinationer och förintande mörk energi.",
  voiceBarks: {
    special: "GOON BLAST!",
    super: "MAXIMUM GOON ACTIVATE!",
    win: "TOO WEAK TO RESIST!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_knee",
    throw: "throw",
    special1: "goon_blast",
    special2: "deadline_kick",
    super: "maximum_goon_super",
  },
  moves: {
    lp: {
      id: "lp",
      name: "One-Hand Jab",
      startup: 4,
      active: 3,
      recovery: 5,
      damage: 36,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 32,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 45, y: 220, w: 80, h: 50 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "goon_blast", "deadline_kick", "maximum_goon_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Goon Backhand",
      startup: 7,
      active: 4,
      recovery: 13,
      damage: 90,
      hitstun: 17,
      blockstun: 11,
      hitstop: 6,
      pushback: 65,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 45, y: 215, w: 115, h: 65 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["goon_blast", "deadline_kick", "maximum_goon_super"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Degenerate Low",
      startup: 5,
      active: 3,
      recovery: 6,
      damage: 34,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 30,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 20, w: 95, h: 45 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "goon_blast"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Focused Axe Kick",
      startup: 8,
      active: 4,
      recovery: 16,
      damage: 92,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 75,
      knockback: 75,
      launch: 30,
      category: "LOW",
      hitboxes: [{ x: 45, y: 20, w: 135, h: 65 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["maximum_goon_super"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_knee: {
      id: "air_knee",
      name: "Flygande knä",
      startup: 5,
      active: 5,
      recovery: 9,
      damage: 68,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 45,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 140, w: 110, h: 75 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Sprintkast",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 110,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 135,
      knockback: 85,
      launch: 55,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    goon_blast: {
      id: "goon_blast",
      name: "Goon Blast",
      startup: 10,
      active: 4,
      recovery: 18,
      damage: 80,
      hitstun: 16,
      blockstun: 11,
      hitstop: 4,
      pushback: 65,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [],
      projectile: {
        vx: 90,
        vy: 0,
        lifetime: 65,
        hitbox: { x: -25, y: 200, w: 60, h: 50 },
        damage: 80,
        category: "HIGH",
        maxConcurrent: 1,
        hitstun: 16,
        blockstun: 11,
        hitstop: 4,
        pushback: 65,
        meterGainOnHit: 50,
        chip: 18,
      },
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["maximum_goon_super"] },
      airOk: false,
      lowPose: false,
      animation: "special_shot",
    },
    deadline_kick: {
      id: "deadline_kick",
      name: "Goon Axe Surge",
      startup: 8,
      active: 8,
      recovery: 20,
      damage: 110,
      hitstun: 22,
      blockstun: 12,
      hitstop: 6,
      pushback: 85,
      knockback: 80,
      launch: 40,
      category: "MID",
      hitboxes: [{ x: 45, y: 180, w: 150, h: 90 }],
      meterGainOnHit: 65,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 20,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["maximum_goon_super"] },
      airOk: false,
      lowPose: false,
      animation: "special_kick",
    },
    maximum_goon_super: {
      id: "maximum_goon_super",
      name: "MAXIMUM GOON",
      startup: 6,
      active: 12,
      recovery: 28,
      damage: 280,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 180,
      knockback: 150,
      launch: 120,
      category: "MID",
      hitboxes: [{ x: 40, y: 150, w: 270, h: 180 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 60,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 6,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
