import type { CharacterDef } from "@aipuf/contracts";
import { airPunch, crouchKit, DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const TARD: CharacterDef = {
  id: "tard",
  name: "Tård",
  archetype: "tard",
  blurb: "Tung, trög och obehagligt klibbig. Drar in dig och smetar ut dig i närkamp.",
  strengths: ["Command grab-tryck", "Tunga normals", "Skrämmande presence"],
  weaknesses: ["Långsam walk", "Straffas hårt på whiff", "Låg mobilitet"],
  combo: "Jab → låg spark → Smear Grab",
  antiAir: "Tung spark eller hopp-in",
  approach: "Smear in eller hopp-in",
  punish: "Tung box → Smear Grab → Super",
  walkSpeed: 4,
  backWalkSpeed: 3,
  dashSpeed: 16,
  jumpVy: 54,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 18,
  weight: 1100,
  throwDamage: 115,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#78350f", "#fbbf24"],
  animationProfileId: "tard",
  modelUrl: "/models/tard.glb",
  portraitUrl: "/portraits/tard.png",
  tagline: "Klibbig kaos",
  power: 9,
  speed: 4,
  range: 5,
  signature: "Smear Grab",
  superName: "FULL SMEAR",
  playstyle: "Går fram långsamt, smear-grabbar, slammar på plus.",
  voiceBarks: {
    special: "SMEAR!",
    super: "FULL SMEAR!",
    win: "NU ÄR DU KLIBBIG!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_strike",
    throw: "throw",
    special1: "smear_grab",
    special2: "tar_stomp",
    super: "full_smear",
  },
  moves: {
    ...crouchKit(["lk", "hp", "hk", "smear_grab", "full_smear"]),
    air_punch: airPunch("Tjärkrok"),
    lp: {
      id: "lp",
      name: "Sticky Jab",
      startup: 4,
      active: 3,
      recovery: 6,
      damage: 37,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 45, y: 220, w: 80, h: 50 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "smear_grab", "full_smear"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Tar Slap",
      startup: 8,
      active: 4,
      recovery: 14,
      damage: 92,
      hitstun: 17,
      blockstun: 11,
      hitstop: 6,
      pushback: 68,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 50, y: 280, w: 120, h: 70 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["smear_grab", "full_smear"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Goo Tick",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 35,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 32,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 25, w: 100, h: 48 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "smear_grab"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Sludge Sweep",
      startup: 9,
      active: 4,
      recovery: 17,
      damage: 90,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 78,
      knockback: 70,
      launch: 25,
      category: "LOW",
      hitboxes: [{ x: 45, y: 20, w: 140, h: 60 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["full_smear"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_strike: {
      id: "air_strike",
      name: "Luftkladd",
      startup: 6,
      active: 5,
      recovery: 10,
      damage: 68,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 48,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 130, w: 120, h: 75 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Smear Throw",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 115,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 140,
      knockback: 85,
      launch: 55,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    tar_stomp: {
      id: "tar_stomp",
      name: "Tar Stomp",
      startup: 9,
      active: 4,
      recovery: 16,
      damage: 100,
      hitstun: 20,
      blockstun: 12,
      hitstop: 6,
      pushback: 70,
      knockback: 50,
      launch: 20,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 40, w: 120, h: 100 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 18,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["full_smear"] },
      airOk: false,
      lowPose: false,
      animation: "special",
    },
    smear_grab: {
      id: "smear_grab",
      name: "Smear Grab",
      startup: 5,
      active: 3,
      recovery: 22,
      damage: 140,
      hitstun: 28,
      blockstun: 0,
      hitstop: 8,
      pushback: 120,
      knockback: 90,
      launch: 40,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 35, y: 60, w: 100, h: 230 },
      meterGainOnHit: 70,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["full_smear"] },
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    full_smear: {
      id: "full_smear",
      name: "FULL SMEAR",
      startup: 7,
      active: 12,
      recovery: 28,
      damage: 285,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 180,
      knockback: 145,
      launch: 115,
      category: "MID",
      hitboxes: [{ x: 40, y: 140, w: 280, h: 180 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 60,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 7,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
