import type { CharacterDef } from "@aipuf/contracts";
import { airPunch, crouchKit, DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const ZONER_A: CharacterDef = {
  id: "zoner-a",
  name: "Femboyfippe",
  archetype: "zoner-a",
  blurb: "Spacing med lång palm och en kabelfälla på marken. Ingen flygande energi.",
  strengths: ["Lång räckvidd", "Markfälla", "Snabba pokes"],
  weaknesses: ["Tunn i hörnet", "Svag mot grepp", "Fällan tar tid"],
  combo: "Jab → låg spark → Cardiac Tap",
  antiAir: "Tung box eller jump kick",
  approach: "Fälla ut, poke, dash in",
  punish: "Tung box → Super",
  walkSpeed: 6,
  backWalkSpeed: 4,
  dashSpeed: 21,
  jumpVy: 50,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 12,
  weight: 980,
  throwDamage: 110,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#2563eb", "#38bdf8"],
  animationProfileId: "zoner-a",
  modelUrl: "/models/femboyfippe.glb",
  portraitUrl: "/portraits/femboyfippe.png",
  tagline: "The Electric Prodigy",
  power: 5,
  speed: 8,
  range: 9,
  signature: "Cardiac Tap",
  superName: "OVERDRIVE",
  playstyle: "Poke, fälla, chock-palm på nära håll.",
  voiceBarks: {
    special: "TAP!",
    super: "MAXIMUM OVERDRIVE!",
    win: "TOO FAST FOR YOU!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_slash",
    throw: "throw",
    special1: "cardiac_grid",
    special2: "cable_trap",
    super: "super_overdrive",
  },
  moves: {
    ...crouchKit(["lk", "hp", "hk", "cardiac_grid", "super_overdrive"]),
    air_punch: airPunch("Stötkrok"),
    lp: {
      id: "lp",
      name: "Precision Tap",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 40,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 40,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 50, y: 220, w: 90, h: 60 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "cardiac_grid", "super_overdrive"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Defibrillator Palm",
      startup: 11,
      active: 4,
      recovery: 16,
      damage: 90,
      hitstun: 18,
      blockstun: 12,
      hitstop: 6,
      pushback: 80,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 60, y: 280, w: 180, h: 70 }],
      meterGainOnHit: 60,
      meterGainOnBlock: 25,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["cardiac_grid", "super_overdrive"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Soft Step",
      startup: 6,
      active: 3,
      recovery: 8,
      damage: 35,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 30, w: 110, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "cardiac_grid"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Voltage Heel",
      startup: 10,
      active: 4,
      recovery: 18,
      damage: 85,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 90,
      knockback: 60,
      launch: 20,
      category: "LOW",
      hitboxes: [{ x: 50, y: 20, w: 150, h: 60 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["super_overdrive"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_slash: {
      id: "air_slash",
      name: "Luftkabel",
      startup: 7,
      active: 5,
      recovery: 10,
      damage: 65,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 50,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 40, y: 150, w: 130, h: 80 }],
      meterGainOnHit: 45,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Kabelomkoppling",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 110,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 140,
      knockback: 90,
      launch: 60,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    cardiac_grid: {
      id: "cardiac_grid",
      name: "Cardiac Tap",
      startup: 8,
      active: 4,
      recovery: 16,
      damage: 70,
      hitstun: 15,
      blockstun: 11,
      hitstop: 5,
      pushback: 45,
      knockback: 10,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 50, y: 180, w: 140, h: 70 }],
      advance: 8,
      meterGainOnHit: 48,
      meterGainOnBlock: 18,
      meterCost: 0,
      chip: 8,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward", "dash"],
      cancels: { hit: ["super_overdrive"] },
      airOk: false,
      lowPose: false,
      animation: "special",
    },
    cable_trap: {
      id: "cable_trap",
      name: "Fiberskydd",
      startup: 15,
      active: 4,
      recovery: 20,
      damage: 60,
      hitstun: 18,
      blockstun: 14,
      hitstop: 4,
      pushback: 70,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [],
      zone: {
        lifetime: 90,
        hitbox: { x: 120, y: 0, w: 100, h: 260 },
        damage: 60,
        category: "MID",
        maxConcurrent: 1,
        hitstun: 18,
        blockstun: 14,
      },
      meterGainOnHit: 40,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 10,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "special_trap",
    },
    super_overdrive: {
      id: "super_overdrive",
      name: "OVERDRIVE",
      startup: 9,
      active: 10,
      recovery: 32,
      damage: 260,
      hitstun: 35,
      blockstun: 22,
      hitstop: 12,
      pushback: 160,
      knockback: 120,
      launch: 90,
      category: "MID",
      hitboxes: [{ x: 50, y: 150, w: 420, h: 140 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 50,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 9,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
