import type { CharacterDef } from "@aipuf/contracts";
import { DEFAULT_HURT_AIR, DEFAULT_HURT_CROUCH, DEFAULT_HURT_STAND, DEFAULT_PUSHBOX } from "./common.ts";

export const ZONER_B: CharacterDef = {
  id: "zoner-b",
  name: "Stinkfiend",
  archetype: "zoner-b",
  blurb: "Giftig zoner som kontrollerar arenan med stinkmoln, markzoner och distanspress som gör det outhärdligt för motståndaren att avancera.",
  strengths: ["Giftzoner som låser marken", "Hög chip-skada", "Tvingar motståndaren att backa"],
  weaknesses: ["Känslig mot snabb rusning", "Lågt hopp", "Begränsade combo-öppnare på nära håll"],
  combo: "Låg spark -> Snabb stöt -> Stinkzon",
  antiAir: "Hög spark eller Stinkridå",
  approach: "Lägg ut Stinkridå och pressa med projektiler",
  punish: "Hög box -> Stinkstorm -> Super",
  walkSpeed: 30,
  backWalkSpeed: 22,
  jumpVy: 100,
  jumpStartup: 4,
  landRecovery: 3,
  airControl: 11,
  weight: 1000,
  throwDamage: 115,
  throwTechWindow: 8,
  pushbox: DEFAULT_PUSHBOX,
  hurtStand: DEFAULT_HURT_STAND,
  hurtCrouch: DEFAULT_HURT_CROUCH,
  hurtAir: DEFAULT_HURT_AIR,
  colors: ["#15803d", "#86efac"],
  animationProfileId: "zoner-b",
  modelUrl: "/models/Xbot.glb",
  tagline: "The Biohazard Hazard",
  power: 6,
  speed: 7,
  range: 10,
  signature: "Silent But Deadly",
  superName: "BIOHAZARD",
  playstyle: "En vidrig och svårfångad zoner som förgiftar luften med stinkmoln och tvingar motståndaren att backa.",
  voiceBarks: {
    special: "SMELL THIS!",
    super: "BIOHAZARD EXTINCTION!",
    win: "TOO NOXIOUS FOR YOU!",
  },
  normals: {
    lp: "lp",
    hp: "hp",
    lk: "lk",
    hk: "hk",
    air: "air_chop",
    throw: "throw",
    special1: "silent_but_deadly",
    special2: "firewall",
    super: "super_biohazard",
  },
  moves: {
    lp: {
      id: "lp",
      name: "Dirty Jab",
      startup: 5,
      active: 3,
      recovery: 7,
      damage: 42,
      hitstun: 12,
      blockstun: 9,
      hitstop: 4,
      pushback: 42,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [{ x: 50, y: 210, w: 85, h: 55 }],
      meterGainOnHit: 30,
      meterGainOnBlock: 15,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["lk", "hp", "hk", "silent_but_deadly", "super_biohazard"] },
      airOk: false,
      lowPose: false,
      animation: "punch_light",
    },
    hp: {
      id: "hp",
      name: "Sweaty Haymaker",
      startup: 10,
      active: 4,
      recovery: 15,
      damage: 85,
      hitstun: 17,
      blockstun: 11,
      hitstop: 6,
      pushback: 75,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [{ x: 60, y: 220, w: 160, h: 65 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 24,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["silent_but_deadly", "firewall", "super_biohazard"] },
      airOk: false,
      lowPose: false,
      animation: "punch_heavy",
    },
    lk: {
      id: "lk",
      name: "Sneaky Shin Kick",
      startup: 6,
      active: 3,
      recovery: 8,
      damage: 38,
      hitstun: 11,
      blockstun: 8,
      hitstop: 4,
      pushback: 35,
      knockback: 0,
      launch: 0,
      category: "LOW",
      hitboxes: [{ x: 40, y: 25, w: 105, h: 50 }],
      meterGainOnHit: 25,
      meterGainOnBlock: 12,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["hk", "silent_but_deadly"] },
      airOk: false,
      lowPose: true,
      animation: "kick_light",
    },
    hk: {
      id: "hk",
      name: "Stink Stomp",
      startup: 11,
      active: 4,
      recovery: 19,
      damage: 90,
      hitstun: 20,
      blockstun: 10,
      hitstop: 5,
      pushback: 85,
      knockback: 70,
      launch: 25,
      category: "LOW",
      hitboxes: [{ x: 50, y: 15, w: 145, h: 60 }],
      meterGainOnHit: 55,
      meterGainOnBlock: 22,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["crouch", "idle"],
      cancels: { hit: ["super_biohazard"] },
      airOk: false,
      lowPose: true,
      animation: "kick_heavy",
    },
    air_chop: {
      id: "air_chop",
      name: "Pakethugg",
      startup: 7,
      active: 4,
      recovery: 11,
      damage: 60,
      hitstun: 14,
      blockstun: 10,
      hitstop: 5,
      pushback: 45,
      knockback: 0,
      launch: 0,
      category: "OVERHEAD",
      hitboxes: [{ x: 45, y: 140, w: 120, h: 75 }],
      meterGainOnHit: 40,
      meterGainOnBlock: 18,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["jump", "fall"],
      cancels: {},
      airOk: true,
      lowPose: false,
      animation: "air_kick",
    },
    throw: {
      id: "throw",
      name: "Portomkoppling",
      startup: 4,
      active: 2,
      recovery: 18,
      damage: 115,
      hitstun: 25,
      blockstun: 0,
      hitstop: 8,
      pushback: 130,
      knockback: 80,
      launch: 55,
      category: "THROW",
      hitboxes: [],
      throwbox: { x: 30, y: 80, w: 90, h: 220 },
      meterGainOnHit: 60,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: true,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "throw",
    },
    silent_but_deadly: {
      id: "silent_but_deadly",
      name: "Silent But Deadly",
      startup: 11,
      active: 4,
      recovery: 20,
      damage: 70,
      hitstun: 15,
      blockstun: 11,
      hitstop: 4,
      pushback: 55,
      knockback: 0,
      launch: 0,
      category: "HIGH",
      hitboxes: [],
      projectile: {
        vx: 95,
        vy: 0,
        lifetime: 65,
        hitbox: { x: -25, y: 190, w: 55, h: 45 },
        damage: 70,
        category: "HIGH",
        maxConcurrent: 1,
        hitstun: 15,
        blockstun: 11,
        hitstop: 4,
        pushback: 55,
        meterGainOnHit: 45,
        chip: 15,
      },
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 0,
      chip: 0,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: { hit: ["super_biohazard"] },
      airOk: false,
      lowPose: false,
      animation: "special_shot",
    },
    firewall: {
      id: "firewall",
      name: "Stinkmoln",
      startup: 16,
      active: 4,
      recovery: 22,
      damage: 65,
      hitstun: 20,
      blockstun: 16,
      hitstop: 4,
      pushback: 80,
      knockback: 0,
      launch: 0,
      category: "MID",
      hitboxes: [],
      zone: {
        lifetime: 100,
        hitbox: { x: 140, y: 0, w: 90, h: 280 },
        damage: 65,
        category: "MID",
        maxConcurrent: 1,
        hitstun: 20,
        blockstun: 16,
      },
      meterGainOnHit: 40,
      meterGainOnBlock: 20,
      meterCost: 0,
      chip: 12,
      knockdown: false,
      allowed: ["idle", "walkForward", "walkBackward"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "special_trap",
    },
    super_biohazard: {
      id: "super_biohazard",
      name: "BIOHAZARD",
      startup: 8,
      active: 12,
      recovery: 30,
      damage: 270,
      hitstun: 35,
      blockstun: 24,
      hitstop: 12,
      pushback: 170,
      knockback: 130,
      launch: 85,
      category: "MID",
      hitboxes: [{ x: 45, y: 140, w: 450, h: 160 }],
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      meterCost: 1000,
      chip: 55,
      knockdown: true,
      invulnStart: 0,
      invulnEnd: 8,
      allowed: ["idle", "walkForward", "walkBackward", "attackStartup", "attackActive"],
      cancels: {},
      airOk: false,
      lowPose: false,
      animation: "super",
    },
  },
};
